apiVersion: apps/v1
kind: Deployment
metadata:
  name: car
  labels:
    app: car
spec:
  replicas: 1
  selector:
    matchLabels:
      app: car
  template:
    metadata:
      labels:
        app: car
    spec:
      containers:
      - name: car
        image: ccr.ccs.tencentyun.com/coolcar_travel/car:1.0.2
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8081
        resources:
          limits:
            cpu: 100m
            memory: 128Mi
        env:
          - name: MONGO_URI
            valueFrom:
              configMapKeyRef:
                key: mongo
                name: endpoints
          - name: AMQP_URI
            valueFrom:
              configMapKeyRef:
                key: amqp
                name: endpoints
          - name: CAR_ADDR
            valueFrom:
              configMapKeyRef:
                key: car
                name: endpoints
          - name: TRIP_ADDR
            valueFrom:
              configMapKeyRef:
                key: trip
                name: endpoints
          - name: AI_ADDR
            valueFrom:
              configMapKeyRef:
                key: ai
                name: endpoints
      imagePullSecrets:
        - name: qcloudregistrykey
---
apiVersion: v1
kind: Service
metadata:
  name: car
spec:
  selector:
    app: car
  ports:
    - name: grpc
      protocol: TCP
      port: 8081
    - name: http
      protocol: TCP
      port: 8080
  type: LoadBalancer

